# AUTOGENERATED FILE

MEASUREMENT_DESCRIPTIONS = {
    "height_cm": """Vertical measurement from crown of head to floor (without shoes)""",
    "chest_cm": """Horizontal circumference at fullest part of chest (tape parallel to floor)""",
    "bust_cm": """Horizontal circumference under arms across bust apex (parallel to floor)""",
    "waist_cm": """Horizontal circumference at natural waist (narrowest torso point)""",
    "hip_cm": """Maximum horizontal circumference at hip level (parallel to floor)""",
    "waist_hip_distance_cm": """Vertical distance from natural waist to fullest hip point""",
    "bust_height_cm": """Vertical distance from shoulder-neck point to bust apex""",
    "breast_distance_cm": """Horizontal distance between nipple centers""",
    "bust_radius_cm": """Vertical distance from bust apex to underbust line""",
    "shoulder_underbust_distance_cm": """Vertical distance from shoulder-neck point to underbust line""",
    "front_waist_length_cm": """Vertical distance from shoulder-neck point to front waist""",
    "back_waist_length_cm": """Vertical distance from cervicale (neck base) to back waist""",
    "back_width_cm": """Horizontal distance between armhole creases (arms relaxed)""",
    "back_shoulder_cm": """Horizontal distance between shoulder joints (back view)""",
    "around_armhole_cm": """Circumference through shoulder joint, armpit, and back-break point""",
    "around_bicep_cm": """Maximum circumference of upper arm (midway between shoulder and elbow)""",
    "around_elbow_cm": """Circumference around elbow joint (arm bent at 90 degrees)""",
    "around_wrist_cm": """Circumference around wrist bone (hand relaxed)""",
    "hand_entry_cm": """Circumference around widest part of hand (excluding thumb)""",
    "elbow_length_cm": """Vertical distance from shoulder joint to elbow point""",
    "sleeve_length_cm": """Vertical distance from shoulder joint to sleeve hem""",
    "dress_knee_length_cm": """Vertical distance from shoulder-neck point to knee (front)""",
    "dress_full_length_cm": """Vertical distance from shoulder-neck point to floor (front)""",
    "skirt_knee_length_cm": """Vertical distance from waist to knee (front view)""",
    "skirt_full_length_cm": """Vertical distance from waist to floor (front view)""",
    "neck_sweetheart_front_distance_cm": """Vertical distance from neck base to sweetheart neckline""",
    "neck_sweetheart_back_distance_cm": """Vertical distance from neck base to back neckline""",
    "around_neck_cm": """Circumference at base of neck (above collarbone)""",
    "flare_out_cm": """Vertical distance from waist to mermaid skirt flare point""",
    "walking_step_cm": """Circumference around flare-out point for walking ease""",
    "pant_waist_cm": """Horizontal circumference at pant waist level""",
    "pant_hip_cm": """Maximum horizontal circumference at hip level for pants""",
    "pant_waist_hip_distance_cm": """Vertical distance from pant waist to hip""",
    "pant_body_rise_cm": """Vertical distance from waist to chair seat (sitting position)""",
    "pant_outseam_cm": """Vertical distance from waistband to hem (outside leg)""",
    "pant_inseam_cm": """Vertical distance from crotch seam to hem (inside leg)""",
    "pant_full_length_cm": """Vertical distance from waist to floor (full-length)""",
    "pant_knee_length_cm": """Vertical distance from waist to knee (side view)""",
    "pant_calf_length_cm": """Vertical distance from waist to calf midpoint""",
    "pant_ankle_length_cm": """Vertical distance from waist to ankle bone""",
    "pant_high_ankle_length_cm": """Vertical distance from waist to high ankle point""",
    "around_thigh_cm": """Circumference at fullest part of thigh""",
    "around_knee_cm": """Circumference around knee cap (leg slightly bent)""",
    "around_calf_cm": """Circumference at fullest part of calf""",
    "around_high_ankle_cm": """Circumference above ankle bone""",
    "around_ankle_cm": """Circumference at narrowest ankle point""",
    "foot_entry_cm": """Circumference around widest part of foot""",
}

CUSTOM_RULES = {
    "waist_cm": [
        {
            "formula": "hip_cm * 0.7",
            "tolerance": 0.05,
            "notes": """Female: 0.65-0.75, Male: 0.85-0.95 (WHO standards)"""
        },
        {
            "formula": "height_cm * 0.43",
            "tolerance": 0.03,
            "notes": """Health assessment guideline (WHO)"""
        },
        {
            "formula": "pant_inseam_cm * 0.35",
            "tolerance": 0.02,
            "notes": """High-rise trouser standard"""
        },
        {
            "formula": "waist_hip_distance_cm * 2.5",
            "tolerance": 0.02,
            "notes": """Corset pattern standard"""
        },
    ],
    "pant_inseam_cm": [
        {
            "formula": "height_cm * 0.5",
            "tolerance": 0.03,
            "notes": """Vaia dataset ±3cm allowance for posture variations"""
        },
    ],
    "bust_height_cm": [
        {
            "formula": "bust_radius_cm * 2.0",
            "tolerance": 0.5,
            "notes": """Pattern drafting standard (ISO 8559-1:2020)"""
        },
        {
            "formula": "front_waist_length_cm * 1.5",
            "tolerance": 0.2,
            "notes": """Bodice balance tolerance"""
        },
        {
            "formula": "bust_cm * 0.6",
            "tolerance": 0.02,
            "notes": """Bra cup positioning standard"""
        },
        {
            "formula": "height_cm * 0.3",
            "tolerance": 0.01,
            "notes": """Vertical bust position standard"""
        },
        {
            "formula": "bust_cm * 0.6",
            "tolerance": 0.01,
            "notes": """Bra band position standard"""
        },
    ],
    "dress_knee_length_cm": [
        {
            "formula": "front_waist_length_cm + skirt_knee_length_cm",
            "tolerance": 1.2,
            "notes": """Dressmaking ease allowance (ASTM D6960)"""
        },
    ],
    "dress_full_length_cm": [
        {
            "formula": "front_waist_length_cm + skirt_full_length_cm",
            "tolerance": 1.5,
            "notes": """Full-length dress standard (ISO 3635)"""
        },
        {
            "formula": "height_cm * 0.9",
            "tolerance": 0.02,
            "notes": """Maxi dress standard (±2cm hem allowance"""
        },
    ],
    "around_neck_cm": [
        {
            "formula": "waist_cm * 0.37",
            "tolerance": 0.8,
            "notes": """±0.8cm tolerance for collar styles"""
        },
        {
            "formula": "chest_cm * 0.4",
            "tolerance": 0.3,
            "notes": """Shirt collar standard"""
        },
        {
            "formula": "height_cm * 0.2",
            "tolerance": 0.01,
            "notes": """Turtleneck standard"""
        },
    ],
    "around_thigh_cm": [
        {
            "formula": "hip_cm * 0.6",
            "tolerance": 1.5,
            "notes": """±1.5cm for athletic/muscular builds"""
        },
        {
            "formula": "waist_cm * 0.6",
            "tolerance": 0.05,
            "notes": """Athletic wear standard (0.6±0.05)"""
        },
        {
            "formula": "around_calf_cm * 1.5",
            "tolerance": 0.5,
            "notes": """Tapered pant standard"""
        },
        {
            "formula": "around_ankle_cm * 2.0",
            "tolerance": 0.3,
            "notes": """Bell-bottom trouser standard"""
        },
    ],
    "front_waist_length_cm": [
        {
            "formula": "height_cm * 0.26",
            "tolerance": 0.02,
            "notes": """Ergonomic clothing standard (EN 13402)"""
        },
        {
            "formula": "back_waist_length_cm * 1.2",
            "tolerance": 0.1,
            "notes": """Bodice block proportion (ISO 8559-2)"""
        },
        {
            "formula": "bust_height_cm * 1.3",
            "tolerance": 0.01,
            "notes": """Empire line dress standard"""
        },
        {
            "formula": "height_cm * 0.4",
            "tolerance": 0.01,
            "notes": """Cropped jacket standard"""
        },
    ],
    "around_bicep_cm": [
        {
            "formula": "bust_cm * 0.25",
            "tolerance": 0.4,
            "notes": """Sleeve cap adjustment tolerance"""
        },
        {
            "formula": "back_shoulder_cm * 0.25",
            "tolerance": 0.02,
            "notes": """Tailored jacket standard"""
        },
    ],
    "pant_body_rise_cm": [
        {
            "formula": "pant_outseam_cm - pant_inseam_cm",
            "tolerance": 1.0,
            "notes": """Trouser drafting standard ±1cm"""
        },
        {
            "formula": "waist_cm * 0.35",
            "tolerance": 0.02,
            "notes": """Low-rise trouser standard"""
        },
    ],
    "around_knee_cm": [
        {
            "formula": "hip_cm * 0.5",
            "tolerance": 1.0,
            "notes": """Jeans/legging design tolerance"""
        },
        {
            "formula": "around_thigh_cm * 0.6",
            "tolerance": 0.1,
            "notes": """Athletic legging standard"""
        },
        {
            "formula": "around_ankle_cm * 1.5",
            "tolerance": 0.2,
            "notes": """Jodhpur trouser standard"""
        },
    ],
    "elbow_length_cm": [
        {
            "formula": "sleeve_length_cm - 0_2_height_cm",
            "tolerance": 0.5,
            "notes": """Sleeve articulation allowance"""
        },
        {
            "formula": "height_cm * 0.25",
            "tolerance": 0.02,
            "notes": """Long-sleeve garment standard"""
        },
    ],
    "around_elbow_cm": [
        {
            "formula": "height_cm * 0.08",
            "tolerance": 0.02,
            "notes": """Jacket/coat pattern standard"""
        },
        {
            "formula": "around_bicep_cm * 0.85",
            "tolerance": 0.1,
            "notes": """Sleeve articulation standard"""
        },
    ],
    "skirt_knee_length_cm": [
        {
            "formula": "height_cm * 0.4",
            "tolerance": 0.03,
            "notes": """Knee-length skirt proportion ±3cm"""
        },
        {
            "formula": "skirt_full_length_cm * 0.6",
            "tolerance": 0.02,
            "notes": """Knee-length proportion"""
        },
    ],
    "around_calf_cm": [
        {
            "formula": "around_thigh_cm * 0.7",
            "tolerance": 1.0,
            "notes": """Tapered leg design tolerance"""
        },
        {
            "formula": "around_ankle_cm * 1.5",
            "tolerance": 0.2,
            "notes": """Boot fit tolerance"""
        },
    ],
    "height_cm": [
        {
            "formula": "back_shoulder_cm * 6.5",
            "tolerance": 0.3,
            "notes": """Ergonomic shoulder proportion"""
        },
    ],
    "skirt_full_length_cm": [
        {
            "formula": "height_cm * 0.5",
            "tolerance": 0.03,
            "notes": """Midi skirt proportion standard"""
        },
    ],
    "bust_cm": [
        {
            "formula": "waist_cm * 1.5",
            "tolerance": 0.1,
            "notes": """Hourglass body standard (1.5±0.1)"""
        },
        {
            "formula": "waist_cm * 1.2",
            "tolerance": 0.03,
            "notes": """Standard hourglass tolerance"""
        },
    ],
    "chest_cm": [
        {
            "formula": "10 + waist_cm",
            "tolerance": 0.8,
            "notes": """Menswear standard ±0.8cm"""
        },
    ],
    "back_waist_length_cm": [
        {
            "formula": "front_waist_length_cm * 0.9",
            "tolerance": 0.01,
            "notes": """Spinal curvature adjustment"""
        },
    ],
    "breast_distance_cm": [
        {
            "formula": "bust_cm * 0.5",
            "tolerance": 0.2,
            "notes": """Bra cup spacing standard"""
        },
    ],
    "hip_cm": [
        {
            "formula": "around_calf_cm * 1.8",
            "tolerance": 0.8,
            "notes": """Pencil skirt drafting tolerance"""
        },
        {
            "formula": "around_knee_cm * 2.0",
            "tolerance": 0.5,
            "notes": """Fitted skirt standard"""
        },
        {
            "formula": "5 + bust_cm",
            "tolerance": 1.0,
            "notes": """Balanced body type standard"""
        },
        {
            "formula": "5 + bust_cm",
            "tolerance": 1.0,
            "notes": """Balanced figure standard (±1cm)"""
        },
    ],
    "around_wrist_cm": [
        {
            "formula": "height_cm * 0.05",
            "tolerance": 0.01,
            "notes": """Bracelet/watch compatibility"""
        },
        {
            "formula": "hand_entry_cm * 0.6",
            "tolerance": 0.1,
            "notes": """Glove design standard"""
        },
        {
            "formula": "around_bicep_cm * 0.6",
            "tolerance": 0.1,
            "notes": """Long sleeve standard"""
        },
        {
            "formula": "around_ankle_cm * 1.1",
            "tolerance": 0.05,
            "notes": """Proportion balance standard"""
        },
    ],
    "around_ankle_cm": [
        {
            "formula": "around_calf_cm * 0.6",
            "tolerance": 0.3,
            "notes": """Skinny jean standard"""
        },
        {
            "formula": "around_thigh_cm * 0.5",
            "tolerance": 0.2,
            "notes": """Wide-leg trouser standard"""
        },
        {
            "formula": "waist_cm * 0.15",
            "tolerance": 0.02,
            "notes": """High-waisted trouser standard"""
        },
    ],
    "around_armhole_cm": [
        {
            "formula": "bust_cm * 0.3",
            "tolerance": 0.4,
            "notes": """Sleeve mobility allowance"""
        },
    ],
    "wrist_depth": [
        {
            "formula": "wrist_width * 0.8",
            "tolerance": 0.05,
            "notes": """Glove articulation standard"""
        },
    ],
    "pant_knee_length_cm": [
        {
            "formula": "height_cm * 0.5",
            "tolerance": 0.02,
            "notes": """Cropped trouser standard"""
        },
    ],
}
